name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CI_IMAGE: ghcr.io/agapemiteu/manualai-ci:latest

jobs:
  build-ci-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ env.CI_IMAGE }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push CI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ci/Dockerfile
          push: true
          tags: ${{ env.CI_IMAGE }}

  frontend-lint:
    needs: build-ci-image
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.build-ci-image.outputs.image }}
    env:
      NEXT_PUBLIC_API_URL: https://agapemiteu-manualai.hf.space
    steps:
      - uses: actions/checkout@v4

      - name: Install Node dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build frontend
        run: npm run build

  backend-test:
    needs: build-ci-image
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.build-ci-image.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r api/requirements.txt

      - name: Run backend tests
        run: python api/test_improvements.py
